#!/bin/sh

# stolen from https://gist.github.com/srebalaji/4b23fb62f6ce26c17b73ca07ae7cfc67#file-git-lazypush

message=$1 # First parameter will be the commit message
currentBranch=$(git symbolic-ref --short -q HEAD) # Getting the current branch

if [ ! -z "$1" ] # checking if the commit message is present. If not then aborting.
then
  git add .
  git commit -m "$message"
  git push origin $currentBranch
else
  echo "Commit message is not provided"
fi